<?php 
define("DB_HOST","localhost");
//define("DB_HOST","hktd18k.99aiji.net");
define("DB_USER","root");
//define("DB_USER","youxiaomimysql");
define("DB_PWD","root");
//define("DB_PWD","97da485c");
define("DB_DBNAME","you");
//define("DB_DBNAME","youxiaomimysql");
define("DB_CHARSET","utf8");
